title: Joe Uong
description: Data Systems, Analytics Engineering, and Institutional Data
theme: jekyll-theme-midnight

url: "https://portfolio.joeuong.com"
baseurl: ""

author: Joe Uong

markdown: kramdown
kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
    values:
      layout: "default"